import 'package:flutter/material.dart';
import 'package:gpt_prompt_builder/features/home/domain/models/prompt_category_models.dart';

List<PromptCategory> promptCategories = <PromptCategory>[
  PromptCategory(
    category: 'Общие',
    icon: Icons.menu_book,
    subCategories: [
      PromptSubCategory(subCategories: "Повседневные задачи"),
      PromptSubCategory(subCategories: "Организация времени"),
      PromptSubCategory(subCategories: "Лайфхаки и советы"),
      PromptSubCategory(subCategories: "Мотивация и психология"),
      PromptSubCategory(subCategories: "Коммуникация и общение"),
      PromptSubCategory(subCategories: "Новости и тренды"),
      PromptSubCategory(subCategories: "Советы по здоровью и фитнесу"),
      PromptSubCategory(subCategories: "Управление финансами"),
      PromptSubCategory(subCategories: "Творчество и вдохновение"),
    ],
  ),
  PromptCategory(
    category: 'Креатив и тексты',
    icon: Icons.edit_note,
    subCategories: [
      PromptSubCategory(subCategories: "Написание статей и блогов"),
      PromptSubCategory(subCategories: "Сценарии и рассказы"),
      PromptSubCategory(subCategories: "Поэзия и лирика"),
      PromptSubCategory(subCategories: "Рекламные тексты и слоганы"),
      PromptSubCategory(subCategories: "Копирайтинг"),
      PromptSubCategory(subCategories: "Редактирование и корректура"),
      PromptSubCategory(subCategories: "Креативные задания и игры"),
      PromptSubCategory(subCategories: "Создание мемов и шуток"),
      PromptSubCategory(subCategories: "Креативное мышление"),
      PromptSubCategory(subCategories: "Контент для соцсетей"),
    ],
  ),
  PromptCategory(
    category: 'ИИ и технологии',
    icon: Icons.smart_toy,
    subCategories: [
      PromptSubCategory(subCategories: "Машинное обучение"),
      PromptSubCategory(subCategories: "Нейросети и глубокое обучение"),
      PromptSubCategory(subCategories: "Робототехника"),
      PromptSubCategory(subCategories: "Обработка естественного языка (NLP)"),
      PromptSubCategory(subCategories: "Компьютерное зрение"),
      PromptSubCategory(subCategories: "Технологии распознавания речи"),
      PromptSubCategory(subCategories: "Автоматизация и боты"),
      PromptSubCategory(subCategories: "Будущее ИИ"),
      PromptSubCategory(subCategories: "Этические вопросы ИИ"),
      PromptSubCategory(subCategories: "Обзор и новости технологий"),
    ],
  ),
  PromptCategory(
    category: 'Разработка кода',
    icon: Icons.code,
    subCategories: [
      PromptSubCategory(subCategories: "Веб-разработка"),
      PromptSubCategory(subCategories: "Мобильная разработка"),
      PromptSubCategory(subCategories: "Backend и серверы"),
      PromptSubCategory(subCategories: "Frontend и UI/UX"),
      PromptSubCategory(subCategories: "Языки программирования"),
      PromptSubCategory(subCategories: "Базы данных и SQL"),
      PromptSubCategory(subCategories: "API и интеграции"),
      PromptSubCategory(subCategories: "Тестирование и отладка"),
      PromptSubCategory(subCategories: "DevOps и CI/CD"),
      PromptSubCategory(subCategories: "Open Source и коллаборация"),
    ],
  ),

  PromptCategory(
    category: 'Обучение и развитие',
    icon: Icons.school,
    subCategories: [
      PromptSubCategory(subCategories: "Саморазвитие и личностный рост"),
      PromptSubCategory(subCategories: "Изучение языков"),
      PromptSubCategory(subCategories: "Онлайн-курсы и платформы"),
      PromptSubCategory(subCategories: "Методики запоминания"),
      PromptSubCategory(subCategories: "Навыки критического мышления"),
      PromptSubCategory(subCategories: "Планирование учебы"),
      PromptSubCategory(subCategories: "Образовательные игры"),
      PromptSubCategory(subCategories: "Психология обучения"),
      PromptSubCategory(subCategories: "Тренировка мозга"),
      PromptSubCategory(subCategories: "Менторство и коучинг"),
      PromptSubCategory(subCategories: "Развитие креативности"),
    ],
  ),
  PromptCategory(
    category: 'Бизнес и карьера',
    icon: Icons.business_center,
    subCategories: [
      PromptSubCategory(subCategories: "Стартапы и предпринимательство"),
      PromptSubCategory(subCategories: "Лидерство и управление командой"),
      PromptSubCategory(subCategories: "Маркетинг и продажи"),
      PromptSubCategory(subCategories: "Финансовое планирование"),
      PromptSubCategory(subCategories: "Карьерный рост и смена профессии"),
      PromptSubCategory(subCategories: "Нетворкинг и связи"),
      PromptSubCategory(subCategories: "Личные бренды"),
      PromptSubCategory(subCategories: "Переговоры и убеждение"),
      PromptSubCategory(subCategories: "Аналитика и стратегии"),
      PromptSubCategory(subCategories: "Юридические аспекты бизнеса"),
    ],
  ),
  PromptCategory(
    category: 'Графика и визуалы',
    icon: Icons.image,
    subCategories: [
      PromptSubCategory(subCategories: "Дизайн интерфейсов (UI/UX)"),
      PromptSubCategory(subCategories: "Иллюстрация и арт"),
      PromptSubCategory(subCategories: "Фотография и обработка фото"),
      PromptSubCategory(subCategories: "Видео и монтаж"),
      PromptSubCategory(subCategories: "Анимация и моушн-дизайн"),
      PromptSubCategory(subCategories: "3D-моделирование"),
      PromptSubCategory(subCategories: "Визуализация данных"),
      PromptSubCategory(subCategories: "Цветовые схемы и теория цвета"),
      PromptSubCategory(subCategories: "Типографика"),
      PromptSubCategory(subCategories: "Инфографика"),
    ],
  ),
  PromptCategory(
    category: 'Культура и переводы',
    icon: Icons.public,
    subCategories: [
      PromptSubCategory(subCategories: "Литература и книги"),
      PromptSubCategory(subCategories: "История и традиции"),
      PromptSubCategory(subCategories: "Искусство и музеи"),
      PromptSubCategory(subCategories: "Музыка и театры"),
      PromptSubCategory(subCategories: "Кинематограф"),
      PromptSubCategory(subCategories: "Языки и диалекты"),
      PromptSubCategory(subCategories: "Переводческие техники"),
      PromptSubCategory(subCategories: "Межкультурные коммуникации"),
      PromptSubCategory(subCategories: "Фольклор и мифология"),
      PromptSubCategory(subCategories: "Современные культурные тренды"),
    ],
  ),
  PromptCategory(
    category: 'Развлечения',
    icon: Icons.videogame_asset,
    subCategories: [
      PromptSubCategory(subCategories: "Игры и геймдизайн"),
      PromptSubCategory(subCategories: "Кино и сериалы"),
      PromptSubCategory(subCategories: "Музыка и плейлисты"),
      PromptSubCategory(subCategories: "Юмор и мемы"),
      PromptSubCategory(subCategories: "Путешествия и туризм"),
      PromptSubCategory(subCategories: "Хобби и DIY"),
      PromptSubCategory(subCategories: "Косплей и фан-культура"),
      PromptSubCategory(subCategories: "Вечеринки и события"),
      PromptSubCategory(subCategories: "Книги и комиксы"),
      PromptSubCategory(subCategories: "Видеоблоги и стриминг"),
    ],
  ),
];
